#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

bspc monitor -d 1 2 3 4 5

bspc config focused_border_color '#f6d079'
bspc config normal_border_color '#0B0B0B'
bspc config active_border_color '#0B0B0B'

bspc config border_width	2
bspc config window_gap          11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a zoom state=floating center=on follow=on border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

.config/polybar/launch.sh
 picom --config .config/picom/picom.conf &
 xdo lower -N Polybar
#/home/hyr00l/.local/bin/wal -i $(cat /home/hyr00l/.scripts/current_wallpaper) -a 75
